### ISSUE TITLE
Using in Windows 10.

### ISSUE THREAD

**Issue by sullyme** [adnanh/webhook#130]
I'm using Windows 10 and I want simple command like this:

`powershell -Command "$PSVersionTable.PSVersion"`

or maybe I need to launch .ps1 files.

If I use this hook:

```
[
  {
    "id": "webhook-test",
    "execute-command": "test.ps1",
    "command-working-directory": "."
  }
]
```

with test.ps1 like this:

```
Write-Verbose "Testing..." -verbose
```

I get this from webhook:

```
[webhook] 2017/05/04 16:13:11 webhook-test got matched
[webhook] 2017/05/04 16:13:11 webhook-test hook triggered successfully
[webhook] 2017/05/04 16:13:11 2017-05-04T16:13:11+02:00 | 200 |          797.6µs | 192.168.16.101:9001 | GET /hooks/webhook-test
[webhook] 2017/05/04 16:13:11 executing test.ps1 (test.ps1) with arguments ["test.ps1"] and environment [] using . as cwd
[webhook] 2017/05/04 16:13:11 command output:
[webhook] 2017/05/04 16:13:11 error occurred: fork/exec test.ps1: %1 is not a valid Win32 application.
[webhook] 2017/05/04 16:13:11 finished handling webhook-test
```

If I use:

`"execute-command": "powershell -Command \"$PSVersionTable.PSVersion\"",`

I get:

```
[webhook] 2017/05/04 16:19:25 executing powershell -Command "$PSVersionTable.PSVersion" (powershell -Command "$PSVersionTable.PSVersion") with arguments ["powershell -Command \"$PSVersionTable.PSVersion\""] and environment [] using . as cwd
[webhook] 2017/05/04 16:19:25 command output:
[webhook] 2017/05/04 16:19:25 error occurred: exec: "powershell -Command \"$PSVersionTable.PSVersion\"": executable file not found in %PATH%
```

**Why?**

**Comment by avluis** [comment]
You got two different behaviors here because of the script call itself (Windows sucks at running PowerShell scripts for some reason)...

Scenarios:
1. You are missing the script handler here -- makes sense, powershell scripts are still scripts.
2. The command runner can't resolve either `powershell` or `"powershell -Command \"$PSVersionTable.PSVersion\""` using info from your PATH variable.

I'll assume you can launch your powershell script from your command prompt as well as from the run command. So in order to work around this, you could:

- Call a cmd prompt to handle your powershell script and its arguments.
- Verify that Windows is resolving your commands by running them from `Run` or `Cmd`.
- Play with quotes -- these will make or break your script call, specially when the path contains spaces.

Here is a powershell snippet I keep handy when working with spaces:
`powershell -noexit "& ""C:\path\to_my\script.ps1"""`

I hope this info gets you closer to your answer~

**Comment by adnanh** [comment]
Command should be `powershell` and you should pass rest of the arguments via `pass-arguments-to-command`. To pass string use `{ "source": "string", "name": "firstargument" }` as specified in https://github.com/adnanh/webhook/wiki/Hook-Definition

**Comment by moorereason** [comment]
When I run powershell scripts in Windows Task Scheduler, I use the following:

```
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command "& C:\path\to\script.ps1 ; exit $LASTEXITCODE"
```
