### ISSUE TITLE
Running scripts sequentially for the same payload with different arguments

### ISSUE THREAD

**Issue by sridhar-vadlamani-ck** [adnanh/webhook#134]
For the same event, I want to run multiple scripts.

`hands_on_check` with the `body` and `statuses_url` and a `WIP` check with `title` and the `statuses_url`.

I know it's possible by having a unified script which does both and takes in the 3 inputs. But I want to separate it out a bit.

Is this possible at the moment?

**Comment by adnanh** [comment]
Old versions of webhook used to support multiple hooks with the same id, but it only brought complications to the overall architecture and the expected behavior so they are out now.

The best approach is to have a wrapper script that receives the 3 inputs and then calls your other scripts with the appropriate arguments.

**Comment by sridhar-vadlamani-ck** [comment]
I was hoping for something like an array for 
```json
    [
    {
    "execute-command": "/home/checks.py",
    "command-working-directory": "/home/webhooks/",
    "pass-arguments-to-command": [
      {
        "source": "payload",
        "name": "pull_request.statuses_url"
      },
      {
        "source": "payload",
        "name": "pull_request.body"
      },
      {
        "source": "payload",
        "name": "pull_request.title"
      }
    ]
    },
    {
    "execute-command": "/home/check2s.py",
    "command-working-directory": "/home/webhooks/",
    "pass-arguments-to-command": [
      {
        "source": "payload",
        "name": "pull_request.statuses_url"
      }
      ]
    }
    ]
```
