### ISSUE TITLE
Allow soft failures for signature validation

### ISSUE THREAD

**Issue by hassanbabaie** [adnanh/webhook#234]
@adnanh @moorereason 

Heads up, I've spotted an error in the development branch it is only impacting the new Scalr Signature rule. 

This is is when using the OR match rule which seems to only work off the top one in the list for example in the below only A would work.:

```
"trigger-rule":{
                "or":[
                        {
                        "match":{
                                "type": "scalr-signature",
                                "secret": "secret **A** inserted here"
                                }
                        },
                        {
                        "match":{
                                "type": "scalr-signature",
                                "secret": "secret **B** inserted here"
                                }
                        }
                ]
        }
```

I think I need to make an update in the sections below related to 'scalr-signature' in order to be able to support the use of the OR and AND MATCH RULES.

I'm going to take a look now but please let me know if you think this might be the case.

@AloysAugustin please also let me know if you by chance spot this message and spot the missing line

**EXTRACT FROM hook.go**

```
// AndRule will evaluate to true if and only if all of the ChildRules evaluate to true
type AndRule []Rules

// Evaluate AndRule will return true if and only if all of ChildRules evaluate to true
func (r AndRule) Evaluate(headers, query, payload *map[string]interface{}, body *[]byte, remoteAddr string) (bool, error) {
	res := true

	for _, v := range r {
		rv, err := v.Evaluate(headers, query, payload, body, remoteAddr)
		if err != nil {
			return false, err
		}

		res = res && rv
		if !res {
			return res, nil
		}
	}

	return res, nil
}

// OrRule will evaluate to true if any of the ChildRules evaluate to true
type OrRule []Rules

// Evaluate OrRule will return true if any of ChildRules evaluate to true
func (r OrRule) Evaluate(headers, query, payload *map[string]interface{}, body *[]byte, remoteAddr string) (bool, error) {
	res := false

	for _, v := range r {
		rv, err := v.Evaluate(headers, query, payload, body, remoteAddr)
		if err != nil {
			return false, err
		}

		res = res || rv
		if res {
			return res, nil
		}
	}

	return res, nil
}
```

**Comment by AloysAugustin** [comment]
Hi @hassanbabaie , good catch.

I think the problem is in the implementation of the OrRule, and exists for all rules, not just the Scalr signature check.
In hook.go, line 703, during the evaluation of the OrRule, if an error is returned when evaluating a rule, then the next rules are not evaluated. Since most rules return a non-nil error when the rule doesn't match, the evaluation will stop at the first failed rule. This goes somewhat against the point of an Or rule... :-)
I think we should just remove lines 703-705 from `hook.go`.

The AndRule evaluation function does the same thing, and it can also be a problem there (although less frequently). For instance a Not rule can return true with a non-nil error. The error will cause the evaluation of the And rule to fail, even though it should not. The root of the issue is arguably in the Not rule here though. 
For this one I'm not sure what the best solution is, we could modify the NotRule to not return an error when its logical result is true, or we could also remove the `err != nil` check from the AndRule evaluation.

@adnanh what are your thoughts on this?

**Comment by moorereason** [comment]
In general, an error should stop evaluation of the hook. Period.

The real question is whether or not the signature checks (SHA1, SHA256, Scalr) should return errors simply because the signature doesn't match.  That's really not an error, per say -- it's a validation failure.  I would think we could just log the cause of the failure and `return false, nil`.  That way @hassanbabaie could setup an OrRule to match multiple signatures.

**Comment by hassanbabaie** [comment]
Hi @moorereason, quick sense check, I think what you're saying is we would probably change this behavior for all three signature based match rules and not just the new scalr one as all three would cause an error especially on the OR check?

So report this more as a validation fail versus a error? I'll see have a go over the weekend to see how it looks byt my update will be more of a local hack.

@AloysAugustin @adnanh This make sense to me, what's your thoughts?

Thanks

Hass

**Comment by hassanbabaie** [comment]
Just to confirm; Changing line 149:

**FROM:**
`return false, &SignatureError{providedSignature}`

**TO:**
`return false, nil`

This has resolved the issue using OR matching

However I now have a situation that even if the match fails it's reporting back a **HTTP 200** instead of **HTTP 5xx**. I guess this is expected given I have removed the error and I guess this is what @AloysAugustin was getting at.

Please let me know your thoughts

Thanks

Hass

**Comment by moorereason** [comment]
You can use `trigger-rule-mismatch-http-response-code` to return a different HTTP response code.

**Comment by hassanbabaie** [comment]
Pull request created #236

**Comment by moorereason** [comment]
After giving my earlier suggestion some more thought, I want to make another proposal.

Given:

- The current implementation precludes testing for more than one signature validation in a given hook definition (using an OrRule).
- Changing the default error return value of all signature validation functions would be a major breaking change.  We should avoid that.
- The Scalr signature validation should not be logically different from the existing signature validations.

Therefore, my proposal is:

- Add a new configuration option that allows failed signature validations to be treated as simple validation failures instead of errors.  Something like `trigger-signature-validation-soft-failures`.
- Update the validation logic to ignore `SignatureError` errors if the above config option is enabled.  Or have the signature validation funcs not return an error in that case.

This would keep from breaking backward compatibility while allowing OrRule logic with multiple signatures.

@adnanh, I'd like to know what you think about this issue and proposal.

**Comment by hassanbabaie** [comment]
Sounds good @moorereason this would obviously be well beyond my copying and pasting skills but might be good.

FYI, I built a hook with the "nil" setting  from my development branch so this has got us out of the woods for now

Thanks

Hass

**Comment by adnanh** [comment]
@moorereason Sounds good to me!
