### ISSUE TITLE
[question] Is it possible to write to standard error from a hook command, and see it in the terminal?

### ISSUE THREAD

**Issue by Adnn** [adnanh/webhook#261]
I cannot find this in the documentation, but I observe that even though my command (python and shell scripts) write to the standard output, nothing is shown in the terminal running webhook (actually in a container, but should not matter I guess).

Is that expected behaviour?

Is there a way to have it shown in terminal?

**Comment by adnanh** [comment]
Are you running webhook with the `-verbose` flag?

**Comment by kutayzorlu** [comment]
webhook works   very nice.. perfekt.  Mit freundliche Grüßen. Fh Dipl.-Ing. Kutay Zorlu Software & System Eng. DE: +49 162 825 33 66 me@kutayzorlu.com **************************************************************** * Was ist ein Cloud ?Netzwerk? Software ? System ?  * Erfahren Sie mehr unter… http://www.kutayzorlu.com * **************************************************************** *** Diese E-Mail ist allein für den bezeichneten Adressaten bestimmt. Sie kann rechtlich vertrauliche Informationen enthalten. Wenn Sie diese E-Mail irrtümlich erhalten haben, informieren Sie bitte unverzüglich den Absender per E-Mail und löschen Sie diese E-Mail von Ihrem Computer, ohne Kopien anzufertigen. Vielen Dank. *** *** This email is for the exclusive use of the addressee. It may contain legally privileged information. If you have received this message in error, please notify the sender by email immediately and delete the message from your computer without making any copies. Thank you. *** *** Bu e-posta, alıcıyı münhasıran kullanmak içindir. Yasal olarak imtiyazlı bilgi içerebilir. Bu mesajı yanlışlıkla aldıysanız, lütfen göndereni e-postayla hemen bilgilendirin ve mesajı kopyalar olmadan bilgisayarınızdan silin. Teşekkür ederim. *** *** Это электронное письмо предназначено исключительно для адресатов. Он может содержать юридически привилегированную информацию. Если вы получили это сообщение по ошибке, немедленно сообщите об этом отправителю по электронной почте и удалите сообщение с вашего компьютера без каких-либо копий. Благодарю вас. *** ---- On Fr, 06 Jul 2018 11:55:39 +0200 Adnan Hajdarević <notifications@github.com> wrote ---- Are you running webhook with the -verbose flag? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Adnn** [comment]
@adnanh My bad, the standard output is correctly shown on screen with `-verbose` flag. But the standard error is **not**.

Is it expected behaviour?

**Comment by Adnn** [comment]
Okay, so I investigated further, and the problem of **stderr** not showing in the terminal is present with the package distributed through Ubuntu package manager (currently on bionic), but not when building webhook directly.

So the workaround is simple, just took me a lot of time to realize that one should not rely on the pre-packaged version of webhook.

Thank you for the very useful project!

**Comment by adnanh** [comment]
@Adnn Sorry for the late response. 

Yeah, I was about to ask which version of webhook were you using, since capturing of the stderr was added just recently.

Unfortunately, the ubuntu package is outdated (like most of them in the ubuntu ecosystem :().

Glad it works for you now!

P.S. kutayzorlu doesn't look like a spambot to me, but a non-native english speaker :-)
