### ISSUE TITLE
What's a best practice for sending back command results that take long time?

### ISSUE THREAD

**Issue by MadDud** [adnanh/webhook#291]
Hi, nice software. 

Consider following:
- a result of a time-consuming command needs to be sent back to a client.
- a command line executed by webhook takes too long and it can't be sent in the response with include-`command-output-in-response`.
- a client can receive data too with API (let's say it's Redmine).

```             
+-------+   send hook  +-------+
| client|  +---------> |webhook|
+---+---+              +---+---+
    ^                      |
    +----------------------+
       Send result in HTTP POST
```

Is it possible that a adnanh/webhook can facilitate the second part "Send result in HTTP POST" without implementation of some wrapup commanads like `curl -d @-?`?

**Comment by adnanh** [comment]
Hi, the best practice in general for long running operation is exactly the way you've described it, instead of waiting for the result, you send the result when it's ready. Webhook's job is to accept the incoming webhook, parse the payload and invoke the proper script/command. It's script's/command's job to implement the handling logic, including sending the response back to the desired location.

Best regards,
Adnan

**Comment by MadDud** [comment]
OK. thank you.

**Comment by brickcatena** [comment]
Is there an example on how to get command results that don't take a long time sent back? I have had trouble finding even that.

**Comment by brickcatena** [comment]
> Is there an example on how to get command results that don't take a long time sent back? I have had trouble finding even that.
I found this example most helpful: https://github.com/adnanh/webhook/issues/136#issuecomment-304349740
