### ISSUE TITLE
Recommendations for production deployment 

### ISSUE THREAD

**Issue by ichauhan91** [adnanh/webhook#308]
Hi,

This is my first time working with this great app. My only requirement is to listen to web hook alerts from various sources and execute python scripts for each. I have some experience working with python flask applications where we use gunicorn and nginx for concurrency, load balancing etc. 

It would be great if anyone can shed light on how well does this app scale for concurrent requests or any recommendation for production deployment? Also I have read that Golang by design is concurrent unlike python's GIL problem.

Thank you for any suggestion.

**Comment by hassanbabaie** [comment]
@ichauhan91 we're using it in production and it's working great but we're not hitting it with large concurrent loading. 

However that said from a "concurrent" processing perspective it could just be scaled horizontally if you design it right. ours don't care about any other one, we just grab the logs

**Comment by moorereason** [comment]
You shouldn't have a problem with concurrency.  It's part of webhook's fundamental design.  There's actually a request (#148) for the opposite issue were people want to limit concurrency.

As far as deployment guidance, you don't need anything like nginx to get concurrency.

However, I do use nginx as a frontend proxy to webhook, but that's because I have instances of webhook for different servers/projects (nginx acts like a router in this sense).  I do this mainly so that I can change the topology in the background without having to update hook configs at 3rd party sites.
