### ISSUE TITLE
question: error code and output

### ISSUE THREAD

**Issue by sebest** [adnanh/webhook#31]
Hello,

1/ Do you plan on returning an error code other than 200 when the command fail?
2/ Do you plan on adding an option to return the output of the command on the HTTP response

if no, would you accept code for any of these 2 features?

best

**Comment by adnanh** [comment]
Thank you for your writeup,
few days ago, my coworker came to me with the same request.
Although I wasn't all up for it at that moment, I do agree now that they should be incorporated into webhook.

I would, however, make those features optional, instead of default. Having said that, I would gladly accept your PR-s :-)
