### ISSUE TITLE
Add an option to get unmodified payload

### ISSUE THREAD

**Issue by AndrewSav** [adnanh/webhook#330]
From: https://github.com/adnanh/webhook/issues/329#issuecomment-525469547

In some scenarios formatting of payload matters, for example, when an aplication that is calling webhook signs the payload with an algorythm not supported by webhook. 

In order for a hook script author to be able to check the signature they need access to excact byte-to-byte copy of the payload.

Webhook puts json/web-form payload through json serializer which removes all formatting, making it impossible for a hook script to accurately check the signature.

This is a request to make the exact payload available to hook scripts.

**Comment by irons** [comment]
For the benefit of anyone else trying to figure out why webhook passes null payloads for AWS SNS topic subscription confirmations, AWS [proudly sends a JSON POST body with a text/plain content-type](https://docs.aws.amazon.com/sns/latest/dg/sns-http-https-endpoint-as-subscriber.html). The hook definition has to presumptively treat it as application/json in order to read it:

`"incoming-payload-content-type": "application/json"`

I only figured this out after spending too many hours wondering why I was failing to build a hook definition to dump everything it was sent in a POST body. Eventually I noticed that [Referencing Request Values](https://github.com/adnanh/webhook/blob/master/docs/Referencing-Request-Values.md) describes `Payload` as "JSON or form-value encoded", which makes `entire-payload` kind of an inadequate descriptor.

So, +1 to this request, with the addendum that I'd like to be able to see the payload no matter what kind of data it is, even if it's syntactically invalid. To drop the payload even before verbose mode can log it is a recipe for headaches. 

Thanks for your time.

**Comment by irons** [comment]
The next morning it turned out that SNS updates were key-value pairs delivered as text/plain, so this tool couldn't be used as a receiver.

**Comment by AndrewSav** [comment]
@irons what updates? The page you linked clearly says that the notifications are sent in JOSN format. It never mentions word "update". What do you mean?

**Comment by adnanh** [comment]
Tagging this with #356 which should hopefully provide a powerful mechanism to craft a solution to the problem.

**Comment by moorereason** [comment]
This issue should be resolved by #486 which was just released in v2.8.0.
