### ISSUE TITLE
Get a Property with dots in the name from a JSON Payload

### ISSUE THREAD

**Issue by otmos** [adnanh/webhook#333]
I just love this piece of software , upon using it , i came across a use case that i couldn't get to work , which is having the following JSON Payload :
```json
"properties": {
    "sonar.analysis.buildnumber": "1567096760967"
  }
```
and i want to send this build number as an argument to the command , but couldn't get that to work.
i tried using the full name , referencing it with the index but in vain.

Thank you

**Comment by moorereason** [comment]
Good question.  That's not currently supported since we naively treat dots as parent-child boundaries (see `hook.GetParameter`).

How are you trying to reference that value in your hook config?  Or how do you propose to access the value?

## Quick Braindump

### Option 1: Quote property value

```json
      {
        "source": "payload",
        "name": "blah.properties.\"sonar.analysis.buildnumber\""
      }
```
We'd have to write a string parser for this or use regex.

### Option 2: Make the delimiter configurable

```json
    "object-delimiter": "|",
    "pass-arguments-to-command":
    [
      {
        "source": "payload",
        "name": "blah|properties|sonar.analysis.buildnumber"
      }
```
This would be simple and flexible.

**Comment by otmos** [comment]
Both suggestions landed the same error :
[webhook] 2019/09/03 10:19:30 [8ed707] error extracting command arguments: couldn't retrieve argument for {Source:payload Name:project|name EnvName: Base64Decode:false}
[webhook] 2019/09/03 10:19:30 [8ed707] error extracting command arguments: couldn't retrieve argument for {Source:payload Name:properties|sonar.analysis.buildnumber EnvName: Base64Decode:false}

I managed to create a workaround , if i get the whole properties value , i get the following result :
[map[sonar.analysis.buildnumber:1123324545]
So using Sed in the shell file , i was able to extract the value that i want

**Comment by moorereason** [comment]
The options I gave before are only ideas for enhancing `webhook` functionality.  I didn't mean for you to try them.  😃 

I'm glad you found a work-around, but I'd like to keep this enhancement request since I believe it's an important improvement.

**Comment by adnanh** [comment]
I like the idea with the object separator, but the issue would still persist if the user explicitly specifies it as `.`.

We could also try to modify the `hook.GetParameter` to check if the full property path exists, and return it, otherwise it should continue, breaking it down until it reaches the exact match?

@moorereason unrelated to this issue, I was thinking of writing a spec for the next version (v3?) which  would tackle some of the issues such as:
 1. easing up the configuration on users (probably creating a more expressive DSL).
This would allow us to extend webhook with new features more easily, and get rid of the ugly JSON. YAML wasn't the right move to solving the configuration readability.
 1. adding rate limiting option
 2. introducing middleware plugins (so we can allow for a bit of payload manipulation, customized validators etc...)
 3. querying the status of async hook executions

What do you think?

**Comment by moorereason** [comment]
@adnanh,
I considered that option, too, but didn't include it for whatever reason.  I think it may work and be more intuitive.

As to v3, all of that sounds pretty straight-forward with the exception of the DSL.  The current config is tedious (mainly the trigger rules), but I'm curious what you're thinking of in terms of a DSL.  I generally prefer existing formats to DSLs for config files.  DSLs can be more concise and expressive, but they come with their own cognitive load and learning curve (and maintenance cost).  I look forward to see your proposal.  😉
