### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by jewelvadim** [adnanh/webhook#565]
I have go1.7.5 in /usr/local/
```
$ go version
go version go1.17.5 linux/amd64
```
settings in .profile:
```
export PATH=$PATH:/usr/local/go/bin
```
```
$ go build github.com/adnanh/webhook
**no required module provides package github.com/adnanh/webhook: go.mod file not found in current directory or any parent directory; see 'go help modules'**

$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build586084061=/tmp/go-build -gno-record-gcc-switches"
```
where is a problem?

And I don't have go folder in /root/ with pkg and bin subfolders

**Comment by moorereason** [comment]
> `$ go build github.com/adnanh/webhook`

You can't build webhook outside of a working package directory.  If you want to install `webhook`, you can do

```
$ go install github.com/adnanh/webhook@latest
```

**Comment by DavidJapan** [comment]
I am really struggling with webhooks this time. I've used it for years, actually, but I'm installing a new droplet on DigitalOcean and having trouble. I tried to create a 2nd hook for a new repository and got "hook got matched, but didn't get triggered because the trigger rules were not satisfied" errors, so I followed issue #524 which seems to suggest that the Ubuntu packaged version 2.6.9 is the problem and I need to upgrade to 2.8. I tried using Snap, but couldn't find where Snap had installed webhook. I then tried to build from source using go and got stuck with this issue. I can't understand what I'm supposed to do after I run 

`$ go install github.com/adnanh/webhook@latest`

Where is the executable file and where are the config files? Could you please change the readme file because it clearly states that we have to run `$ go build github.com/adnanh/webhook`, but where do you run it? I'm trying to get webhook working. I'm not trying to learn Go.

**Comment by moorereason** [comment]
@DavidJapan, the path of least resistance is to download the [pre-built release binaries](https://github.com/adnanh/webhook/releases/tag/2.8.0) for your architecture.

As for where `go install` installs to, see the following from `go help install`:

> Executables are installed in the directory named by the GOBIN environment
variable, which defaults to $GOPATH/bin or $HOME/go/bin if the GOPATH
environment variable is not set.
